import { db } from "@/firebaseConfig";
import type { ProfileResponse, UserProfile } from "@/types/types";
import {
  addDoc,
  collection,
  doc,
  getDoc,
  getDocs,
  query,
  serverTimestamp,
  updateDoc,
  where,
} from "firebase/firestore";


const COLLECTION_NAME = "users";

export const createUserProfile = async (user: UserProfile) => {
  try {
    return await addDoc(collection(db, COLLECTION_NAME), user);
  } catch (err) {
    console.error(err);
  }
};

export const getUserProfile = async (userId: string) => {
  try {
    const q = query(
      collection(db, COLLECTION_NAME),
      where("userId", "==", userId)
    );
    const querySnapshot = await getDocs(q);
    let tempData: ProfileResponse = {};
    if (querySnapshot.size > 0) {
      querySnapshot.forEach((doc) => {
        const userData = doc.data() as UserProfile;
        /*doc.id is the id of the document auto generated by firestore. as in mongodb id not kept inside key value pair but individually in document. can get id like this of already created document. */
        tempData = {
          id: doc.id,
          ...userData,
        };
      });
      return tempData;
    } else {
      console.log("No such document");
      return null;
    }
  } catch (error) {
    console.error(error);
  }
};

export const updateUserProfile = async (id: string, user: UserProfile) => {
  const docRef = doc(db, COLLECTION_NAME, id);
  return await updateDoc(docRef, {
    ...user,
  });
};

export const getAllUsers = async (userId: string) => {
  try {
    const querySnapshot = await getDocs(collection(db, COLLECTION_NAME));
    const tempArr: ProfileResponse[] = [];
    if (querySnapshot.size > 0) {
      querySnapshot.forEach((doc) => {
        const userData = doc.data() as UserProfile;
        const responeObj: ProfileResponse = {
          id: doc.id,
          ...userData,
        };
        tempArr.push(responeObj);
      });
      /*below will return all users except the logged in user. also used in admin UserTable to not show admin. used in suggested friends/UserList. in friends/UserList also won't show admn coz admin won't go to userdashboard to create profile, for inbuilt auth too some properties like photos, displayName etc. are optional in signup, in this project we update these by createUserProfile.  getAllUsers gets users from users collection which is created by createUserProfile in EditProfile.tsx.*/
      return tempArr.filter((item) => item.userId != userId);
    } else {
      console.log("No such documents");
    }
  } catch (error) {
    console.error(error);
  }
};

// lastseen update to know  online users
export const updateLastSeen = async (userId: string) => {
      if (!userId) return;

      try {
        const q = query(collection(db, COLLECTION_NAME), where("userId", "==", userId));
        const querySnapshot = await getDocs(q);

        if (!querySnapshot.empty) {
          const userDoc = querySnapshot.docs[0];
          await updateDoc(userDoc.ref, {
            lastSeen: serverTimestamp(),
          });
        }
        
      } catch (err) {
        console.error("Failed to update lastSeen:", err);
      }
    };

